on:
  push:
    branches:
      - master1



jobs:
  build: 
    runs-on: ubuntu-latest


    steps:
      - name: 'laravel1'
        run: pwd

      - name: ' printing folder'
        run: ls
      
